import { IColor } from '../models/color';
import { IBooleanFilterOption, IStringFilterOption } from '../models/filter';

export const brightnessOptions: IStringFilterOption[] = [
  {
    id: 1,
    value: 'light',
    name: 'Light',
  },
  {
    id: 2,
    value: 'dark',
    name: 'Dark',
  },
];

export const warmHueOptions: IStringFilterOption[] = [
  {
    id: 1,
    value: 'red',
    name: 'Red',
  },
  {
    id: 2,
    value: 'orange',
    name: 'Orange',
  },
  {
    id: 3,
    value: 'yellow',
    name: 'Yellow',
  },
];

export const coolHueOptions: IStringFilterOption[] = [
  {
    id: 1,
    value: 'green',
    name: 'Green',
  },
  {
    id: 2,
    value: 'blue',
    name: 'Blue',
  },
  {
    id: 3,
    value: 'purple',
    name: 'Purple',
  },
];

export const triadHueOptions: IStringFilterOption[] = [
  {
    id: 1,
    value: 'red',
    name: 'Red',
  },
  {
    id: 2,
    value: 'yellow',
    name: 'Yellow',
  },
  {
    id: 3,
    value: 'blue',
    name: 'Blue',
  },
];

export const booleanOptions: IBooleanFilterOption[] = [
  {
    id: 1,
    value: true,
    name: 'True',
  },
  {
    id: 1,
    value: false,
    name: 'False',
  },
];

export const colorOptions: IColor[] = [
  {
    id: 1,
    hue: 'red',
    temperature: 'warm',
    brightness: 'light',
    value: 'lightcoral',
    name: 'Light Coral',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 2,
    hue: 'red',
    temperature: 'warm',
    brightness: 'light',
    value: 'lightpink',
    name: 'Light Pink',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 3,
    hue: 'red',
    temperature: 'warm',
    brightness: 'light',
    value: 'indianred',
    name: 'Indian Red',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 4,
    hue: 'red',
    temperature: 'warm',
    brightness: 'medium',
    value: 'red',
    name: 'Red',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 5,
    hue: 'red',
    temperature: 'warm',
    brightness: 'medium',
    value: 'crimson',
    name: 'Crimson',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 6,
    hue: 'red',
    temperature: 'warm',
    brightness: 'dark',
    value: 'darkred',
    name: 'Dark Red',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 7,
    hue: 'red',
    temperature: 'warm',
    brightness: 'dark',
    value: 'firebrick',
    name: 'Fire Brick',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 8,
    hue: 'red',
    temperature: 'warm',
    brightness: 'dark',
    value: 'maroon',
    name: 'Maroon',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 9,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'light',
    value: 'bisque',
    name: 'Bisque',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 10,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'light',
    value: 'moccasin',
    name: 'Moccasin',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 11,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'light',
    value: 'sandybrown',
    name: 'Sandy Brown',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 12,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'medium',
    value: 'orange',
    name: 'Orange',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: true,
  },
  {
    id: 13,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'medium',
    value: 'coral',
    name: 'Coral',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 14,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'dark',
    value: 'peru',
    name: 'Peru',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 15,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'dark',
    value: 'darkorange',
    name: 'Dark Orange',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: true,
  },
  {
    id: 16,
    hue: 'orange',
    temperature: 'warm',
    brightness: 'dark',
    value: 'chocolate',
    name: 'Chocolate',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: true,
  },
  {
    id: 17,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'light',
    value: 'cornsilk',
    name: 'Corn Silk',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 18,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'light',
    value: 'lemonchiffon',
    name: 'Lemon Chiffon',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 19,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'light',
    value: 'lightgoldenrodyellow',
    name: 'Light Goldenrod Yellow',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 20,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'medium',
    value: 'yellow',
    name: 'Yellow',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 21,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'medium',
    value: 'gold',
    name: 'Gold',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 22,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'dark',
    value: 'tan',
    name: 'Tan',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 23,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'dark',
    value: 'goldenrod',
    name: 'Goldenrod',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 24,
    hue: 'yellow',
    temperature: 'warm',
    brightness: 'dark',
    value: 'darkgoldenrod',
    name: 'Dark Goldenrod',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 25,
    hue: 'green',
    temperature: 'cool',
    brightness: 'light',
    value: 'palegreen',
    name: 'Pale Green',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 26,
    hue: 'green',
    temperature: 'cool',
    brightness: 'light',
    value: 'lightgreen',
    name: 'Light Green',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 27,
    hue: 'green',
    temperature: 'cool',
    brightness: 'light',
    value: 'darkseagreen',
    name: 'Dark Sea Green',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 28,
    hue: 'green',
    temperature: 'cool',
    brightness: 'medium',
    value: 'aquamarine',
    name: 'Aquamarine',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 29,
    hue: 'green',
    temperature: 'cool',
    brightness: 'medium',
    value: 'chartreuse',
    name: 'Chartreuse',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 30,
    hue: 'green',
    temperature: 'cool',
    brightness: 'dark',
    value: 'darkgreen',
    name: 'Dark Green',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 31,
    hue: 'green',
    temperature: 'cool',
    brightness: 'dark',
    value: 'darkolivegreen',
    name: 'Dark Olive Green',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: true,
  },
  {
    id: 32,
    hue: 'green',
    temperature: 'cool',
    brightness: 'dark',
    value: 'olivedrab',
    name: 'Olive Drab',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: true,
  },
  {
    id: 33,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'light',
    value: 'lightskyblue',
    name: 'Light Sky Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 34,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'light',
    value: 'lightcyan',
    name: 'Light Cyan',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 35,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'light',
    value: 'powderblue',
    name: 'Powder Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 36,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'medium',
    value: 'cornflowerblue',
    name: 'Cornflower Blue',
    isNamedAfterAFlower: true,
    isNamedAfterAFood: false,
  },
  {
    id: 37,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'medium',
    value: 'deepskyblue',
    name: 'Deep Sky Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 38,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'dark',
    value: 'darkblue',
    name: 'Dark Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 39,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'dark',
    value: 'mediumblue',
    name: 'Medium Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 40,
    hue: 'blue',
    temperature: 'cool',
    brightness: 'dark',
    value: 'midnightblue',
    name: 'Midnight Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 41,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'light',
    value: 'lavender',
    name: 'Lavender',
    isNamedAfterAFlower: true,
    isNamedAfterAFood: false,
  },
  {
    id: 42,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'light',
    value: 'mediumpurple',
    name: 'Medium Purple',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 43,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'light',
    value: 'mediumslateblue',
    name: 'Medium Slate Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 44,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'medium',
    value: 'darkorchid',
    name: 'Dark Orchid',
    isNamedAfterAFlower: true,
    isNamedAfterAFood: false,
  },
  {
    id: 45,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'medium',
    value: 'blueviolet',
    name: 'Blue Violet',
    isNamedAfterAFlower: true,
    isNamedAfterAFood: false,
  },
  {
    id: 46,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'dark',
    value: 'darkslateblue',
    name: 'Dark Slate Blue',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 47,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'dark',
    value: 'darkmagenta',
    name: 'Dark Magenta',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
  {
    id: 48,
    hue: 'purple',
    temperature: 'cool',
    brightness: 'dark',
    value: 'indigo',
    name: 'Indigo',
    isNamedAfterAFlower: false,
    isNamedAfterAFood: false,
  },
];
